import { Box, cssClass } from '@adminjs/design-system';
import { styled } from '@adminjs/design-system/styled-components';
import React from 'react';
import { useSelector } from 'react-redux';
import { SidebarResourceSection } from 'adminjs';
export const SIDEBAR_Z_INDEX = 50;
const resources = [
    {
        id: 'Home',
        name: 'Home',
        href: '/admin',
        navigation: {
            name: null,
            icon: null,
            show: true,
        },
        titleProperty: null,
        resourceActions: [],
        actions: [],
        listProperties: [],
        editProperties: [],
        showProperties: [],
        filterProperties: [],
        properties: {},
    },
    {
        id: 'user-resource',
        name: 'Users',
        href: '/admin/resources/User',
        navigation: {
            name: "Konnect Resources",
            icon: null,
            show: true,
        },
        titleProperty: null,
        resourceActions: [],
        actions: [],
        listProperties: [],
        editProperties: [],
        showProperties: [],
        filterProperties: [],
        properties: {},
    },
    {
        id: 'deposite-resource',
        name: 'deposite',
        href: '/admin/resources/deposite',
        navigation: {
            name: "Konnect Resources",
            icon: null,
            show: true,
        },
        titleProperty: null,
        resourceActions: [],
        actions: [],
        listProperties: [],
        editProperties: [],
        showProperties: [],
        filterProperties: [],
        properties: {},
    },
    {
        id: 'plan_select-resource',
        name: 'Tracking',
        href: '/admin/resources/plan_select',
        navigation: {
            name: "Konnect Resources",
            icon: null,
            show: true,
        },
        titleProperty: null,
        resourceActions: [],
        actions: [],
        listProperties: [],
        editProperties: [],
        showProperties: [],
        filterProperties: [],
        properties: {},
    },
    {
        id: 'plan_select-resource',
        name: 'Opt In',
        href: '/admin/resources/opt_status',
        navigation: {
            name: "Konnect Resources",
            icon: null,
            show: true,
        },
        titleProperty: null,
        resourceActions: [],
        actions: [],
        listProperties: [],
        editProperties: [],
        showProperties: [],
        filterProperties: [],
        properties: {},
    },
    {
        id: 'welcomeBonus-resource',
        name: 'welcome Bonus',
        href: '/admin/resources/WelcomeBonus',
        navigation: {
            name: "Konnect Resources",
            icon: null,
            show: true,
        },
        titleProperty: null,
        resourceActions: [],
        actions: [],
        listProperties: [],
        editProperties: [],
        showProperties: [],
        filterProperties: [],
        properties: {},
    },
    {
        id: 'transaction-resource',
        name: 'Data Transaction',
        href: '/admin/resources/transaction',
        navigation: {
            name: "Konnect Resources",
            icon: null,
            show: true,
        },
        titleProperty: null,
        resourceActions: [],
        actions: [],
        listProperties: [],
        editProperties: [],
        showProperties: [],
        filterProperties: [],
        properties: {},
    },
    {
        id: 'transaction-resource',
        name: 'Failed Data Transaction',
        href: '/admin/resources/failedTransaction',
        navigation: {
            name: "Konnect Resources",
            icon: null,
            show: true,
        },
        titleProperty: null,
        resourceActions: [],
        actions: [],
        listProperties: [],
        editProperties: [],
        showProperties: [],
        filterProperties: [],
        properties: {},
    },
    {
        id: 'transaction-resource',
        name: 'Airtime Transaction',
        href: '/admin/resources/airtime',
        navigation: {
            name: "Konnect Resources",
            icon: null,
            show: true,
        },
        titleProperty: null,
        resourceActions: [],
        actions: [],
        listProperties: [],
        editProperties: [],
        showProperties: [],
        filterProperties: [],
        properties: {},
    },
    {
        id: 'report-resource',
        name: 'Reports',
        href: '/admin/resources/Report',
        navigation: {
            name: "Konnect Resources",
            icon: null,
            show: true,
        },
        titleProperty: null,
        resourceActions: [],
        actions: [],
        listProperties: [],
        editProperties: [],
        showProperties: [],
        filterProperties: [],
        properties: {},
    },
    {
        id: 'transaction-resource',
        name: 'Proccessed',
        href: '/admin/resources/powerTransactions',
        navigation: {
            name: "Electricity Transactions",
            icon: null,
            show: true,
        },
        titleProperty: null,
        resourceActions: [],
        actions: [],
        listProperties: [],
        editProperties: [],
        showProperties: [],
        filterProperties: [],
        properties: {},
    },
    {
        id: 'pending-transaction-resource',
        name: 'Pending',
        href: '/admin/resources/pendingPowerTransactions',
        navigation: {
            name: "Electricity Transactions",
            icon: null,

            show: true,
        },
        titleProperty: null,
        resourceActions: [],
        actions: [],
        listProperties: [],
        editProperties: [],
        showProperties: [],
        filterProperties: [],
        properties: {},
    },
    {
        id: 'DataPlan-resource',
        name: 'Karl Data Plans',
        href: '/admin/resources/FlowDataPlan',
        navigation: {
            name: "Data Plan Prices",
            icon: null,
            show: true,
        },
        titleProperty: null,
        resourceActions: [],
        actions: [],
        listProperties: [],
        editProperties: [],
        showProperties: [],
        filterProperties: [],
        properties: {},
    },
    {
        id: 'DataPlan-resource',
        name: 'Usuf Data Plans',
        href: '/admin/resources/FlowDataPlanUsuf',
        navigation: {
            name: "Data Plan Prices",
            icon: null,
            show: true,
        },
        titleProperty: null,
        resourceActions: [],
        actions: [],
        listProperties: [],
        editProperties: [],
        showProperties: [],
        filterProperties: [],
        properties: {},
    },
    {
        id: 'conversation-resource',
        name: 'Conversations',
        href: '/admin/resources/Conversation',
        navigation: {
            name: "Konnect Resources",
            icon: null,
            show: true,
        },
        titleProperty: null,
        resourceActions: [],
        actions: [],
        listProperties: [],
        editProperties: [],
        showProperties: [],
        filterProperties: [],
        properties: {},
    },
    {
        id: 'media-resource',
        name: 'file Upload',
        href: '/admin/resources/media',
        navigation: {
            name: "Konnect Resources",
            icon: null,
            show: true,
        },
        titleProperty: null,
        resourceActions: [],
        actions: [],
        listProperties: [],
        editProperties: [],
        showProperties: [],
        filterProperties: [],
        properties: {},
    },
    {
        id: 'errorlog-resource',
        name: 'Error Log',
        href: '/admin/resources/error_logs',
        navigation: {
            name: "System",
            icon: null,
            show: true,
        },
        titleProperty: null,
        resourceActions: [],
        actions: [],
        listProperties: [],
        editProperties: [],
        showProperties: [],
        filterProperties: [],
        properties: {},
    },
    {
        id: 'infolog-resource',
        name: 'Info Log',
        href: '/admin/resources/info_logs',
        navigation: {
            name: "System",
            icon: null,
            show: true,
        },
        titleProperty: null,
        resourceActions: [],
        actions: [],
        listProperties: [],
        editProperties: [],
        showProperties: [],
        filterProperties: [],
        properties: {},
    },
    {
        id: 'status-resource',
        name: 'Status',
        href: '/admin/resources/status',
        navigation: {
            name: "System",
            icon: null,
            show: true,
        },
        titleProperty: null,
        resourceActions: [],
        actions: [],
        listProperties: [],
        editProperties: [],
        showProperties: [],
        filterProperties: [],
        properties: {},
    },
    {
        id: 'status-resource',
        name: 'Jobs',
        href: '/admin/resources/Job',
        navigation: {
            name: "System",
            icon: null,
            show: true,
        },
        titleProperty: null,
        resourceActions: [],
        actions: [],
        listProperties: [],
        editProperties: [],
        showProperties: [],
        filterProperties: [],
        properties: {},
    },
    {
        id: 'Msg-resource',
        name: 'Bulk Message',
        href: '/admin/pages/customPage',
        navigation: {
            name: "System",
            icon: null,
            show: true,
        },
        titleProperty: null,
        resourceActions: [],
        actions: [],
        listProperties: [],
        editProperties: [],
        showProperties: [],
        filterProperties: [],
        properties: {},
    },
];
const StyledSidebar = styled(Box) `
  top: 0;
  bottom: 0;
  overflow-y: auto;
  width: ${({ theme }) => theme.sizes.sidebarWidth};
  border-right: ${({ theme }) => theme.borders.default};
  display: flex;
  flex-direction: column;
  flex-shrink: 0;
  z-index: ${SIDEBAR_Z_INDEX};
  background: ${({ theme }) => theme.colors.sidebar};

  transition: left 0.25s ease-in-out;

  &.hidden {
    left: -${({ theme }) => theme.sizes.sidebarWidth};
  }
  &.visible {
    left: 0;
  }
`;
StyledSidebar.defaultProps = {
    position: ['absolute', 'absolute', 'absolute', 'absolute', 'initial'],
};
const SidebarOriginal = (props) => {
    const { isVisible } = props;
    const branding = useSelector((state) => state.branding);
    const pages = useSelector((state) => state.pages);
    return (React.createElement(StyledSidebar, { className: isVisible ? 'visible' : 'hidden', "data-css": "sidebar" },
        React.createElement(Box, { flexGrow: 1, className: cssClass('Resources'), "data-css": "sidebar-resources" },
            React.createElement(SidebarResourceSection, { resources: resources }),
            "`")));
};
export default SidebarOriginal;
